service: get-lucky

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1

plugins:
  - serverless-plugin-chrome

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  getLucky:
    handler: handler.hello
    timeout: 60
    events:
      - schedule: cron(30 6 ? * * *)
    environment:
      LUCKY_REF: ${ssm:LUCKY_REF}
      FAUNADB_KEY: ${ssm:FAUNADB_KEY}
      VULCAN_LOGIN: ${ssm:VULCAN_LOGIN}
      VULCAN_PASSWORD: ${ssm:VULCAN_PASSWORD}

custom:
  chrome:
    flags:
      - --window-size=500,500
      - --hide-scrollbars
    functions:
      - getLucky
