service: get-lucky

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  environment:
    LOGGING: true

plugins:
  - serverless-plugin-chrome

functions:
  getLucky:
    handler: handler.hello
    timeout: 60
    events:
      - schedule: cron(30 5 ? * * *)
    environment:
      LUCKY_REF: ${ssm:LUCKY_REF}
      FAUNADB_KEY: ${ssm:FAUNADB_KEY}
      VULCAN_LOGIN: ${ssm:VULCAN_LOGIN}
      VULCAN_PASSWORD: ${ssm:VULCAN_PASSWORD}

custom:
  chrome:
    flags:
      - --window-size=500,500
      - --hide-scrollbars
    functions:
      - getLucky
