name: Daily get-lucky

on:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@0.0.1
    - name: Download DB
      run: |
        ./scripts/get_database.sh ${{ secrets.DROPBOX_AUTH_JSON }}
        docker run -it --rm \
        -v $PWD/auth.json:/root/.config/dbxcli/auth.json \
        -v $PWD:/backup \
        kairyou/docker-dbxcli get /tmp/numbers.db numbers.db
    - name: Pull image
      run: docker pull zskpoznan/get-lucky
    - name: Run lucky
      run: |
        docker run \
        -e VULCAN_LOGIN=${{ secrets.VULCAN_LOGIN }} \
        -e VULCAN_PASSWORD=${{ secrets.VULCAN_PASSWORD }} \
        -e FAUNADB_KEY=${{ secrets.FAUNADB_KEY }} \
        -e LUCKY_REF=${{ secrets.LUCKY_REF }} \
        -e COLLECT=true \
        -e DB_PATH=/home/numbers.db \
        -v $PWD/numbers.db:/home/numbers.db
        zskpoznan/get-lucky:latest
    - name: Upload db
      run: |
        docker run -it --rm \
        -v $PWD/auth.json:/root/.config/dbxcli/auth.json \
        -v $PWD:/backup \
        kairyou/docker-dbxcli put ./numbers.db /tmp/numbers.db
        
        
