name: Daily get-lucky

on:
  push:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@0.0.1
    - name: Download DB
      run: |
        touch auth.json
        docker run -t --rm \
        -v $PWD/auth.json:/home/auth.json \
        bash:4.4 bash -c 'echo ${{ secrets.DROPBOX_AUTH_JSON }} > /home/auth.json'
        ls
        docker run -t --rm \
        -v $PWD/auth.json:/root/.config/dbxcli/auth.json \
        -v $PWD:/backup \
        --entrypoint="cat /root/.config/dbxcli/auth.json" \
        kairyou/docker-dbxcli #get /tmp/numbers.db numbers.db
    - name: Pull image
      run: docker pull zskpoznan/get-lucky
    - name: Run lucky
      run: |
        docker run \
        -e VULCAN_LOGIN=${{ secrets.VULCAN_LOGIN }} \
        -e VULCAN_PASSWORD=${{ secrets.VULCAN_PASSWORD }} \
        -e FAUNADB_KEY=${{ secrets.FAUNADB_KEY }} \
        -e LUCKY_REF=${{ secrets.LUCKY_REF }} \
        -e COLLECT=true \
        -e DB_PATH=/home/numbers.db \
        -v $PWD/numbers.db:/home/numbers.db
        zskpoznan/get-lucky:latest
    - name: Upload db
      run: |
        docker run -t --rm \
        -v $PWD/auth.json:/root/.config/dbxcli/auth.json \
        -v $PWD:/backup \
        kairyou/docker-dbxcli put ./numbers.db /tmp/numbers.db
        
        
